### ISSUE TITLE
Feat: # of degrees of connections for a phrase

### ISSUE THREAD

**Issue by jp4g** [Mach-34/Grapevine#21]
Adds a new command `grapevine show-connections <phrase_id>`
 - dependent on #17 to use the phrase UID
 - Should return an array of length 7 where it represents # of N degree connections to a phrase
   * should this be dynamic and handle possibility of longer chains of degrees cuz people will mess with infra? for now not handling

For instance, for a phrase X where I have connections with 2 people of degree 3, 3 people of degree 4, and 6 people of degree 5, I will return:
[0, 2, 3, 6, 0, 0, 0].

 - The cli will then display this info for the phrase when `show-connections` is called

**Comment by barryWhiteHat** [comment]
Maybe we should just have a `grapevine get-phrases` that will list all the phrases according to how many peers know them and also shows this information. This command can also accept <phrase_id> and will give you the specific information
